on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

name: Test
jobs:
  test:
    name: Test
    runs-on: macos-26
    # Set timeout to prevent overcharging
    timeout-minutes: 20
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '26.5'
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        run: swift test
